alias l="ls -p --group-directories-first --color=auto"
alias ll="l -lh"
alias la="l -a"
alias mkdir="mkdir -p"
alias ..="cd .."
alias ...="cd ..\.."
alias ....="cd ..\..\.."
alias .....="cd ..\..\..\.."
alias ......="cd ..\..\..\..\.."
alias .......="cd ..\..\..\..\..\.."
